###
POST http://localhost:8095/tickets/create?
    date=2002-08-22&
    visitorUuid=039f0c23-dca3-4cd9-8b08-8e894cc25d86&
    ticketOption=NORMAL&
    ageType=ADULT&
    email={{$random.alphanumeric(8)}}

###
PATCH http://localhost:8092/pointOfInterest/changeOpenStatus?
    uuid=149e17ef-4233-4b69-9e70-7d68f88ecb6b&
    open=false

###
GET http://localhost:8091/pointOfInterest

###
GET http://localhost:8091/attractions

###
GET http://localhost:8091/attractions?
    name=bird

###
GET http://localhost:8091/foodStands

###
GET http://localhost:8091/pointOfInterest?
    name=ice&
    open=true

###
GET http://localhost:8091/attractions

###
GET http://localhost:8091/foodStands

###
POST http://localhost:8180/realms/techtopia/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=client&client_secret=JWO0PfbHBYA74kaMDPDlqMnnJhOiNTLE&username=admin&password=admin&grant_type=password&scope=openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}

### Access secured endpoint via admin role
GET http://localhost:8091/attractions HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET http://localhost:8095/tickets/fetchByEmail?email=jane.doe@gmail.com
Content-Type: application/json

###
GET http://localhost:8094/tickets/ticketStatus?ticketUUID=f6500e86-f240-423b-8980-fb98d0f8426d

###
POST http://localhost:8094/ticketActivity/enter?ticketUUID=f6500e86-f240-423b-8980-fb98d0f8426d

### TicketNotFoundException
POST http://localhost:8094/ticketActivity/enter?ticketUUID=f6500e32-f240-423b-8980-fb98d0f8426d
