###
POST http://localhost:8095/tickets/create?
    date=2002-08-22&
    visitorUuid=039f0c23-dca3-4cd9-8b08-8e894cc25d86&
    ticketOption=NORMAL&
    ageType=ADULT&
    email={{$random.alphanumeric(8)}}

###
PATCH http://localhost:8092/pointOfInterest/changeOpenStatus?
    uuid=149e17ef-4233-4b69-9e70-7d68f88ecb6b&
    open=true

###
GET http://localhost:8091/pointOfInterest

###
GET http://localhost:8091/attractions

###
GET http://localhost:8091/foodStands

###
GET http://localhost:8091/pointOfInterest?
    name=ice&
    open=true

###
GET http://localhost:8091/attractions

###
GET http://localhost:8091/foodStands
