server:
  port: ${PORT:8092}

logging:
  level:
    root: ${SPRING_LOGGING_LEVEL:INFO}

spring:

  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/park_planning}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASS:password}

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/techtopia/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/techtopia

resilience4j:
  retry:
    metrics:
      enabled: true
    instances:
      retryRemote:
        max-attempts: 5
        wait-duration: 1000
  timelimiter:
    instances:
      limitRemote:
        baseConfig: default
    metrics:
      enabled: true
    configs:
      default:
        cancel-running-future: true
        timeout-duration: 5000
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 5
        max-wait-duration: 0
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        sliding-window-type: count_based
        minimum-number-of-calls: 5
